### ISSUE TITLE
Build source maps points to srcc/**.ts but src is not included in final bundle

### ISSUE THREAD

**Issue by Psvensso** [react-dropzone/file-selector#39]
Using via react-dropzone,
v0.2.2

Source maps points to src/* files but src/* is not included. Should either be set to inline-sourcemaps or include the src or don't provide sourcemaps in final build.

dist/es5/index.js.map:1
`"sourceRoot":"","sources":["../../src/index.ts"]`

**What is the current behavior?**
"***app: Failed to parse source map from '****\node_modules\file-selector\src\file-selector.ts' file: Error: ENOENT: no such file or directory, open '****\node_modules\file-selector\src\file-selector.ts'"

**Comment by rolandjitsu** [comment]
@Psvensso thanks for reporting. I will push a fix for that soon.

**Comment by steveHornseyDeveloper** [comment]
FYI if you are using webpack and source-map-loader then you can configure it in the following way to silence the error:

```
   {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
          path.resolve(__dirname, './node_modules/file-selector/dist/es5'),
        ],
     },
```

**Comment by rolandjitsu** [comment]
Should be fixed now. Please update to `0.1.8`/`0.2.3` and let me know if it's ok.

**Comment by jasperprins** [comment]
Thanks. seems to be fixed

**Comment by MattyBalaam** [comment]
I’m not sure if I’m doing something wrong, but we have `"react-dropzone": "^11.2.4"` as a dependency and in our webpack build we are still getting errors, we have a monorepo and are using pnpm

```
Failed to parse source map from '/Users/matthew.balaam/frontend/node_modules/.pnpm/file-selector@0.2.3/node_modules/file-selector/src/file-selector.ts' file: Error: ENOENT: no such file or directory, open '/Users/matthew.balaam/frontend/node_modules/.pnpm/file-selector@0.2.3/node_modules/file-selector/src/file-selector.ts'
@ /Users/matthew.balaam/frontend/node_modules/.pnpm/file-selector@0.2.3/node_modules/file-selector/dist/es5/index.js 1:0-44 1:0-44
@ /Users/matthew.balaam/frontend/node_modules/.pnpm/react-dropzone@11.2.4_react@17.0.1/node_modules/react-dropzone/dist/es/index.js
```
